### ISSUE TITLE
environment.yml

### ISSUE THREAD

**Issue by tmizuhar** [smallpondtom/SDITAA#2]
Could not run python files.

This is what terminal said after 'conda env create -f environment.yml':    

FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'C:\\Users\\TakanoriMizuhara\\Anaconda3\\envs\\SDITAA\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\TakanoriMizuhara\Anaconda3\envs\SDITAA\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TakanoriMizuhara\\AppData\\Local\\Temp\\pip-install-kc_c366q\\llvmlite_7781e257912b4ce18d73d4a77db0648c\\setup.py'"'"'; __file__='"'"'C:\\Users\\TakanoriMizuhara\\AppData\\Local\\Temp\\pip-install-kc_c366q\\llvmlite_7781e257912b4ce18d73d4a77db0648c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TakanoriMizuhara\AppData\Local\Temp\pip-record-db2taxrs\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\TakanoriMizuhara\Anaconda3\envs\SDITAA\Include\llvmlite' Check the logs for full command output.

failed

CondaEnvException: Pip failed

**Comment by smallpondtom** [comment]
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

added pip under dependencies 
try again

**Comment by tmizuhar** [comment]
still unable to run.

 FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'C:\\Users\\TakanoriMizuhara\\Anaconda3\\envs\\SDITAA\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\TakanoriMizuhara\Anaconda3\envs\SDITAA\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TakanoriMizuhara\\AppData\\Local\\Temp\\pip-install-x63f307h\\llvmlite_9d8f154b3f744fef93889f8d6218bc3f\\setup.py'"'"'; __file__='"'"'C:\\Users\\TakanoriMizuhara\\AppData\\Local\\Temp\\pip-install-x63f307h\\llvmlite_9d8f154b3f744fef93889f8d6218bc3f\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TakanoriMizuhara\AppData\Local\Temp\pip-record-yvxinb3x\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\TakanoriMizuhara\Anaconda3\envs\SDITAA\Include\llvmlite' Check the logs for full command output.

failed

CondaEnvException: Pip failed

**Comment by smallpondtom** [comment]
the issue seemed to be the dependencies 
* astropy 
* tle-tools 

Since those were not used in the project I removed them and now anaconda should be able to build the environment from the environment.yml file 

To create the environment, just do 
`conda env create --file environment.yml`
and that should work fine

The output should be like 

```
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: - Ran pip subprocess with arguments:
['C:\\Users\\Tomo\\anaconda3\\envs\\SDITAA-new\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\Tomo\\TomoCode\\SDITAA\\condaenv.t3dp3x1x.requirements.txt']
Pip subprocess output:
Collecting mypy
  Using cached mypy-0.790-py3-none-any.whl (2.4 MB)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
  Using cached typed_ast-1.4.2-cp39-cp39-win_amd64.whl (158 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting sgp4
  Using cached sgp4-2.15-cp39-cp39-win_amd64.whl (152 kB)
Installing collected packages: typing-extensions, typed-ast, mypy-extensions, sgp4, mypy
Successfully installed mypy-0.790 mypy-extensions-0.4.3 sgp4-2.15 typed-ast-1.4.2 typing-extensions-3.7.4.3

done
#
# To activate this environment, use
#
#     $ conda activate SDITAA-new
#
# To deactivate an active environment, use
#
#     $ conda deactivate

```

**Comment by smallpondtom** [comment]
Let me know if it works for you

**Comment by tmizuhar** [comment]
it worked for spg4_debris_trajectory.py but not spg4graphics.py

Error: ModuleNotFoundError: No module named 'cartopy'

**Comment by smallpondtom** [comment]
I deleted 
`import cartopy` 
in the file because it was unnecessary 

It should work  now
